max_width = 88
tab_spaces = 4
fn_params_layout = "Tall"
array_width = 88
chain_width = 88
fn_call_width = 88
# newline_style = "Auto"
# blank_lines_upper_bound = 1
# blank_lines_lower_bound = 0
# hard_tabs = false
# wrap_comments = true
# format_code_in_doc_comments = false
# doc_comment_code_block_width = 80
# normalize_comments = false
# fn_single_line = true
