command: "bash"
programs:
    bash:
        command: "bash"
        restart: ALWAYS
        processes: 3
        success_codes: [0, 1]
        retry_count: 3
        graceful_exit: SIGTERM
        ttk: 5 # seconds
    echo:
        command: "echo"
        args: "the arguments"
    env:
        command: "env"
