command: "bash"
programs:
    first_program:
        command: "bash"
        restart: ALWAYS
        processes: 3
        success_codes: [0, 1]
        retry_count: 3
        graceful_exit: SIGTERM
        ttk: 5 # seconds
    second_program:
        command: "cat"
