command: "bash"
programs:
    bash:
        command: "bash"
        args:
          - "-c"
          - "echo oi; exit 1"
        processes: 1
        # run_at_startup: true,
        # retry_start_count: 3,
        restart: ALWAYS
        graceful_exit: SIGTERM
        ttk: 5 # seconds
        success_codes: [0, 1]
        # succesful_start_after: 5
        # workdir:               /home/user,
        # environment_variables: "VARIABLE=value;OTHER=value",
        # umask:                 420,
    sleep:
        command: "bash"
        args: ['-c', 'sleep 3; exit 42']
    echo:
        command: "echo"
        args: ["the arguments"]
        processes: 3
    weird_wierd:
        command: "ialakkkkkkkazideiaprogram"
        args: ["the arguments"]
        processes: 2
    empty_command:
        command: ""
        args: ["the arguments"]
        processes: 1
    # env:
    #     command: "env"
