command: "bash"
programs:
    bash:
        command: "bash"
        args:
          - "-c"
          - "echo oi"
        processes: 3
        # run_at_startup: true,
        # retry_start_count: 3,
        restart: ALWAYS
        graceful_exit: SIGTERM
        ttk: 5 # seconds
        success_codes: [0, 1]
        # succesful_start_after: 5
        # workdir:               /home/user,
        # environment_variables: "VARIABLE=value;OTHER=value",
        # umask:                 420,
    echo:
        command: "echo"
        args: ["the arguments"]
    env:
        command: "env"
